name: Issues Propagator

on: [push]

jobs:
  diff_parser:
    runs-on: ubuntu-latest
    name: Diff Parsing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: '3'
          show-progress: 'false'
      
      - name: diff extractor
        id: diff_extractor
        uses: malekboubahri2/actions/diff_extractor@main

    outputs:
      diff-result: ${{ steps.diff_extractor.outputs.diff-result }}

  diff_explainer:
    runs-on: ubuntu-latest
    name: Semantic Analysis
    needs: diff_parser
    steps:          
      - name: ai_inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Please explain the following diff in one sentence so it can be sent as a PR to another repository ( DON NOT USE SIMPLE QUOTES!):
            ${{ needs.diff_parser.outputs.diff-result }}
      
      - name: Print Output
        run: echo "${{ steps.inference.outputs.response }}"

    outputs:
      inference-result: ${{ steps.inference.outputs.response }}

  create_issue_F4:
    runs-on: ubuntu-latest
    needs: diff_explainer
    steps:
      - name: Checkout
        env:
            GITHUB_TOKEN: ${{secrets.TARGET_REPO_PAT}}
            ISSUE_TITLE: "Cloned Issue"
            ISSUE_BODY: ${{needs.diff_explainer.outputs.inference-result}}
        run: |
         curl -x POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: appplication/vnd.github.v3+json" \
          https://api.github.com/repos/malekbobauhri2/target_repo/issues \
          -d "$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" '{title: $title, body :$body}')"
