name: Issue Propagator

on: [push]

jobs:
  diff_parser:
    runs-on: ubuntu-latest
    name: Diff Parsing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: '3'
          show-progress: 'false'
      
      - name: diff extractor
        id: diff_extractor
        uses: malekboubahri2/actions/diff_extractor@main

    outputs:
      diff-result: ${{ steps.diff_extractor.outputs.diff-result }}

  diff_explainer:
    runs-on: ubuntu-latest
    name: Semantic Analysis
    needs: diff_parser
    steps:          
      - name: ai_inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Please generate a short decription about this diff commit so an ai could find it and understands its purpose.
            ${{ needs.diff_parser.outputs.diff-result }}
      
      - name: Print Output
        run: echo "${{ steps.inference.outputs.response }}"